### ISSUE TITLE
Прочистка Викшинари 

### ISSUE THREAD

**Issue by mariakaryaeva** [mariakaryaeva/SemRelYARN#5]
Пройтись по викшинари частотным словарем

**Comment by mariakaryaeva** [comment]
**Intital data**
To evaluate the results, we applied a Wiktionary dump containing **59 582** hypernymy and hyponymy pairs.

Частотный список 60 тысяч слов

И род и вид слова из частотного списка => получилось **10 826** пар
Только род из частотного списка => получилось **19 467** пар (дополнительно убрала имена)

**Comment by mariakaryaeva** [comment]
Результаты:
wikionary_clear_60k_rod_freq.txt
wikionary_clear_60k_freq.txt

Викисловарь пары: wikionary_hypernyms.txt
Частотный словарь: 1grams_nkrya_norm.txt

**Comment by pbraslavski** [comment]
в качестве "золотого стандарта" берем 10 тыс.
